services:
  myfeedback.backend:
    image: ${DOCKER_REGISTRY-}myfeedbackbackend
    build:
      context: .
      dockerfile: MyFeedback.Backend/Dockerfile

  myfeedback.login:
    image: ${DOCKER_REGISTRY-}myfeedbacklogin
    build:
      context: .
      dockerfile: MyFeedback.Login/Dockerfile

  mailcatcher:
    image: haravich/fake-smtp-server
 
  myfeedback.blazorfrontend:
    image: ${DOCKER_REGISTRY-}myfeedbackblazorfrontend
    build:
      context: .
      dockerfile: MyFeedback.BlazorFrontend/Dockerfile
    